### ISSUE TITLE
[BUG] - Issues with Config Validation testing suite

### ISSUE THREAD

**Issue by Vyvy-vi** [BeccaLyria/discord-bot#1017]
### What bug did you encounter?

Some of the output given by the `Config Validation` test for the Assertion error for at least 3 responses in `noSelfXP` and `noBotXP` gave erroneous output as - 

>  1) Config Validation
       Becca Responses
         noSelfXP has at least three values:
     AssertionError: noSelfXP only has 8 values
      at Context.<anonymous> (test/config.spec.ts:12:15)
      at processImmediate (node:internal/timers:464:21)

  2) Config Validation
       Becca Responses
         noBotXP has at least three values:
     AssertionError: noBotXP only has 7 values
      at Context.<anonymous> (test/config.spec.ts:12:15)
      at processImmediate (node:internal/timers:464:21)
      
While they both had only 2 values.

### What did you expect to happen?

The error output to say - 

>  1) Config Validation
       Becca Responses
         noSelfXP has at least three values:
     AssertionError: noSelfXP only has 2 values
      at Context.<anonymous> (test/config.spec.ts:12:15)
      at processImmediate (node:internal/timers:464:21)

  2) Config Validation
       Becca Responses
         noBotXP has at least three values:
     AssertionError: noBotXP only has 2 values
      at Context.<anonymous> (test/config.spec.ts:12:15)
      at processImmediate (node:internal/timers:464:21)

### Screenshots

![Screenshot 2021-12-16 at 8 00 52 PM](https://user-images.githubusercontent.com/62864373/146404349-cd00f589-2fbc-42da-9556-5fe09696287f.png)

**Comment by nhcarrigan** [comment]
Oops. This should be a relatively basic fix.

In the [testing file](https://github.com/BeccaLyria/discord-bot/blob/main/test/config.spec.ts), the assert message should be changed:
```diff
- assert(value.length >= 3, `${key} only has ${key.length} values`);
+ assert(value.length >= 3, `${key} only has ${value.length} values`);
```

I'm going to open this one up to first timers.

**Comment by gajendra0180** [comment]
Hello, Can I take up this issue?

>In the testing file, the assert message should be changed: 
>- assert(value.length >= 3, `${key} only has ${key.length} values`);
>+ assert(value.length >= 3, `${key} only has ${value.length} values`);

Is this all that needs to be done?

**Comment by nhcarrigan** [comment]
Yep! There's a couple of assert message lines in that file that needs the change. 🙂
