### ISSUE TITLE
[OTHER] - Update Bookmark Context Command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#1070]
### What would you like to share?

Update this command to no longer send the message content in the bookmark. This will address any potential privacy concerns - since Becca provides a link to the message, we can use that as the single source of truth.

### Additional information

This can be achieved by editing the [command file](https://github.com/BeccaLyria/discord-bot/blob/main/src/contexts/bookmark.ts) to pass the `message.url` into the `setDescription` method, and remove the `addField` call that adds the link.

**Comment by Tejas-Teju** [comment]
I would like to work on this

**Comment by nhcarrigan** [comment]
Go for it! Let us know if you have any questions!

**Comment by Tejas-Teju** [comment]
@nhcarrigan, I believe that I just have to replace message.content to message.url (line 41) and then remove line 50? Please correct me if I am wrong.

**Comment by nhcarrigan** [comment]
Yes, and you can remove the `customSubstring` call as the message link won't be that long.

**Comment by Tejas-Teju** [comment]
bookmarkEmbed.setDescription(
    message.url|| "no content found!"
);

@nhcarrigan, is this fine?

**Comment by nhcarrigan** [comment]
It won't need the fallback, as `message.url` should never be undefined.

**Comment by Tejas-Teju** [comment]
Raised a PR [#1072](https://github.com/BeccaLyria/discord-bot/pull/1072), please review and let me know for any changes.
