### ISSUE TITLE
[FEAT] - Ban Appeal Config

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#1071]
### What feature would you like to see?

We should add a ban appeal configuration option, where a server can provide a link to a Google Form (or other option) for appealing a ban.

Then, when a user is banned, if this config is set, Becca should include the value in the DM sent to the user.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by nhcarrigan** [comment]
Go for it!
