### ISSUE TITLE
[FEAT] - Emote-only on Message Edit

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#1075]
### What feature would you like to see?

We need to mount the emote only listener to the message edit event. To do this, we should import the `emoteListener` in the [`messageUpdate` file](https://github.com/BeccaLyria/discord-bot/blob/main/src/events/messageEvents/messageUpdate.ts). Then, on line 75, we should call it with `await emoteListener(Becca, message, serverConfig)` (below the other listeners).

**Comment by divyakelaskar** [comment]
I'd like to work on this.

**Comment by nhcarrigan** [comment]
Go for it! Let us know if you have any questions!

**Comment by divyakelaskar** [comment]
Sure thing !

**Comment by nhcarrigan** [comment]
Heya! I believe @divyakelaskar is working on it.

**Comment by divyakelaskar** [comment]
Yeah, I'm currently working on it.
