### ISSUE TITLE
[FEAT] - Don't prompt for restricted links if a DM is sent to the concerned sender.

### ISSUE THREAD

**Issue by VishalLudhrani** [BeccaLyria/discord-bot#1088]
### What feature would you like to see?

When the bot restricts unauthorized members to send links that aren't identified as trustworthy, the bot deletes that message and leaves a prompt on the channel where the link was sent.
The bot also sends a DM to the concerned member.
This becomes redundant, and the channels sometimes get filled with such prompts.

### Possible solution 1:
Eliminate the prompts on channel, and keep the notion of sending DM to the concerned sender (including their original message).

### Possible solution 2:
Auto delete the prompt after a delay of few hours, so that the sender knows why the message was deleted instantly.
This will also keep the channel free from prompts.

**Comment by nhcarrigan** [comment]
I like solution two, though I think a few hours is too long. I'm going to go ahead and open this issue up for contribution. A pull requests which resolves this issue will:

- Add a timeout within the [automod listener file](https://github.com/BeccaLyria/discord-bot/blob/main/src/listeners/automod/automodLinks.ts), below line 77.
- That timeout should take an async callback, which looks like `async () => await warning.delete()`.
- The timeout should wait 5 minutes to execute.
- We should also remove the `setUrl` from the `dmEmbed` to avoid sending broken links.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by nhcarrigan** [comment]
Go for it!
