### ISSUE TITLE
[BUG] - Incorrect link in adventure command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#1092]
### What bug did you encounter?

The link for the embed in the `/becca adventure` command is broken and points to the wrong URL.

### What did you expect to happen?

The link should point to `https://beccalyria.com/adventures`.

### Additional information

Within the [handleAdventure file](https://github.com/BeccaLyria/discord-bot/blob/c52a7e262cb393a8dac661ad5c2782a9d5a60de8/src/modules/commands/subcommands/becca/handleAdventure.ts#L39), the URL in `.setUrl` needs to be updated.

**Comment by anky008** [comment]
can I be assigned to this, please

**Comment by nhcarrigan** [comment]
Go for it! Feel free to let us know if you have any questions!

**Comment by anky008** [comment]
so had a question, how do I name the commit? should it be -> "Fixed:[BUG] - Incorrect link in adventure command"

**Comment by nhcarrigan** [comment]
Something like `fix: update link in adventure command`.

**Comment by anky008** [comment]
and after the change, I make a commit to my own copy of the repo and then make a Pull request right?

**Comment by nhcarrigan** [comment]
That's correct yes. Make sure you are on a new branch, don't commit to `main` :)

**Comment by anky008** [comment]
so I have to create a new branch, and then commit there?

**Comment by nhcarrigan** [comment]
That's correct, yes 🙂

**Comment by Vyvy-vi** [comment]
I think this was resolved in #1093
