### ISSUE TITLE
[CHORE] - System path slash direction issues

### ISSUE THREAD

**Issue by plamoni** [BeccaLyria/discord-bot#1110]
### What work needs to be performed?

There are a few places in the code ([example](https://github.com/BeccaLyria/discord-bot/blob/16462f48ea284ada28209d9ff7a6ec37a8bb7cbe/src/utils/loadCommands.ts#L20), [example](https://github.com/BeccaLyria/discord-bot/blob/16462f48ea284ada28209d9ff7a6ec37a8bb7cbe/src/utils/loadContexts.ts)) where system paths are joined using `/`. They should be joined using [`Path.join(...)`](https://nodejs.org/api/path.html#pathjoinpaths), e.g. `join(..., "usr", "local", "src")` instead of `join(..., "usr/local/src")`. This will ensure the correct slash direction for systems that use `\` instead of `/` (e.g. Windows).

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by nhcarrigan** [comment]
Code freeze is lifted - @Vyvy-vi went ahead and assigned you.
