### ISSUE TITLE
[OTHER] - Cleanup Link Detection

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#1114]
### What would you like to share?

Need to:

- Remove the link config, I think. 
- Update the regex to `(([a-z]+:\/\/)?(([a-z0-9-]+\.)+([a-z]{2,})))(:[0-9]{1,5})?[^\s\n]*` - will be more aggressive, but we've had scam links get through which is absolutely unacceptable.
- Possibly strip out `inline code` as well? We currently strip out multi-line code. 

### Additional information

Essentially, this means we'd no longer be maintaining a list of "allowed" and "denied" top level domains - if it looks like a link, Becca will treat it like a link. Servers will still be able to set their own allowlist via regex, but we will not be "prescreening" anything.

**Comment by eddiejaoude** [comment]
I would prefer it to be more strict than let through potential scam links.

People should really be sharing code via GitHub anyway, I am keen to promote people using branches in their open source repos.
