### ISSUE TITLE
[FEAT] - Currency Notification/Reminder

### ISSUE THREAD

**Issue by j-dogcoder** [BeccaLyria/discord-bot#1137]
### What feature would you like to see?

Reminds user when they can claim Currency. (like the karuta bot)

**Comment by nhcarrigan** [comment]
I'd be okay with doing this for the daily/weekly, but probably not the games (every hour is a bit much).

We should take the cache-reliant approach here and mount a timeout when a user claims their daily/weekly to DM them a reminder in 24 hours / 7 days.

**Comment by Vyvy-vi** [comment]
I'd like to try my hand at this.

**Comment by nhcarrigan** [comment]
Go for it!
