### ISSUE TITLE
[OTHER] - MONOISSUE for tracking broken i18n strings

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1151]
### What would you like to share?

Use this issue to post any missed i18n strings you see. Ideally, post a screenshot of the bad string with steps on how you triggered it.

Post only one string per comment please, so we can delete them as they are fixed.

**Comment by nhcarrigan** [comment]
<img width="191" alt="image" src="https://user-images.githubusercontent.com/63889819/152565300-4f01faed-e214-40bc-a14b-68c7d6f073a7.png">

**Comment by nhcarrigan** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/63889819/153075026-01e04347-e7ad-49e3-9393-5168fc7a6650.png">

**Comment by nhcarrigan** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/63889819/153095526-9178941f-0c70-4745-9d0e-b99b71eca5b0.png">

**Comment by nhcarrigan** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/63889819/164391740-558588ea-4d3c-488d-adc7-b432c7b3049d.png">

**Comment by nhcarrigan** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/63889819/172053586-db899ee2-5a74-46a7-8ee4-3b0b6eb453ee.png">

Ping broken in `/community schedule`.

**Comment by naomi-lgbt** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/63889819/182202877-616d874c-28cd-472f-8ba6-a4d86beeb1d2.png">

**Comment by naomi-lgbt** [comment]
Closing this now as the updated `i18next` package with custom type definitions should help prevent these.
