### ISSUE TITLE
[FEAT] - More sassy messages when getting 0 BeccaCoin

### ISSUE THREAD

**Issue by Vyvy-vi** [BeccaLyria/discord-bot#1188]
### What feature would you like to see?

The current `/currency daily` and `/currency weekly` commands plainly report "You've earned 0 BeccaCoin! You now have 0 BeccaCoin!", when someone gets 0 BeccaCoin. This looks too template-y and there's room for more sass here.

Maybe something like - "I don't feel like giving you any BeccaCoin today"?

### Additional information

![Screenshot 2022-03-09 at 11 02 36 AM](https://user-images.githubusercontent.com/62864373/157379341-26838432-4d26-4545-b1cb-546de10ec5d5.png)

**Comment by nhcarrigan** [comment]
This is actually not a bad idea. I'd be in favour of adding this.
