### ISSUE TITLE
[FEAT] - Add Heptagram Scamlinks api for scam detection and reporting

### ISSUE THREAD

**Issue by j-dogcoder** [BeccaLyria/discord-bot#1234]
### What feature would you like to see?

Use the [Heptagram API](https://github.com/Heptagram-Bot-Project/api)'s scamlink endpoints in addition to walshy's endpoint to check for & report spam links.

I develop this API, so am happy to help, and/or PR this.

### Additional information

Conversed with Naomi about this in discord.

<img width="890" alt="contributing - Discord Discord 2rUrf5S9" src="https://user-images.githubusercontent.com/65788728/163279349-c7b4c8f8-c16d-498a-ab49-f76e0beb9ba4.png">

[https://discord.com/channels/778130114772598785/869607198450389062/963196223483969556](https://discord.com/channels/778130114772598785/869607198450389062/963196223483969556)

**Comment by j-dogcoder** [comment]
What's cool about this, is the server strips away the `https:/`/ or `http://` and anything after the root of the domain, so no matter what people send, even if it is without any of the parts, will still be flagged.

And cause it is all done serverside, Becca has less work!

**Comment by nhcarrigan** [comment]
#1238 adds the support for multiple APIs, so we can integrate Heptagram after that's landed.

You'll want to add Heptagram *before* the Sinking Yacht's API call.

**Comment by j-dogcoder** [comment]
After or before Walshy?

**Comment by nhcarrigan** [comment]
Either one.

**Comment by j-dogcoder** [comment]
I'll probably put it before, so we can get some API calls. 😄
