### ISSUE TITLE
[FEAT] - /config set setting:No Levelling Channels able to take multiple values

### ISSUE THREAD

**Issue by j-dogcoder** [BeccaLyria/discord-bot#1256]
### What feature would you like to see?

Allow the `/config set setting:No Levelling Channels value: ` able to take something like this 

![testing - Discord Discord vRJsq0uL](https://user-images.githubusercontent.com/65788728/164458073-a14c4217-ecda-44a3-a3e8-fad40ebd0d74.jpg)

without returning this.

![testing - Discord Discord SPAnvCVd](https://user-images.githubusercontent.com/65788728/164458124-eaca8020-a51c-4505-bb48-227be844516e.jpg)

**Comment by j-dogcoder** [comment]
And other config commands such as `hearts`

**Comment by Vyvy-vi** [comment]
I'd be interesting in working on this.

**Comment by naomi-lgbt** [comment]
We should be able to roll this into #1367, because we'll have setting-specific command options.

We can take the same approach we use for the reaction roles, and shove a bunch of optional parameters into the command. Going to close this issue as linked to the other.
