### ISSUE TITLE
[FEAT] - Add a Starboard System

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1366]
### What feature would you like to see?

Starboard systems are a common way to allow community members to "pin" messages that they find valuable, funny, or otherwise noteworthy. We should implement a starboard system in Becca.

We will need to add three configuration values:
- The channel to use as the starboard (where messages are posted)
- The star emote to listen for (servers can set whatever emote they want, default when unset is ⭐.
- The number of stars a message must receive before it is posted in the above channel.

### Additional information

This is a pretty substantial undertaking - Becca isn't set to listen for reactions, so we'll have to add an event listener for that and ensure we request the gateway intent.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by naomi-lgbt** [comment]
All yours - note that this is blocked until the config system gets overhauled
