### ISSUE TITLE
[CHORE] - Overhaul the Configuration System

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1367]
### What work needs to be performed?

The config system is in desperate need of an overhaul. It was originally written when slash commands were first a thing, and has just had more settings cobbled in there.

Our overhaul will do the following:
- Change the `set`, `view`, and `reset` subcommands to **subcommand groups**
- This will allow us to turn the choices into subcommands
  - In turn, we can start using typed options, removing the need for some of the validation we do on our end.
- We also need to clean up a significant amount of the logic. Adding a new config option should not require as many changes as it does.
- Finally, with a limit of 25 subcommands, we may need to look at recategorizing some of them - as we did with `automod` and `log`.

**Comment by naomi-lgbt** [comment]
The level system configs are probably large enough to justify a separate command.

**Comment by Vyvy-vi** [comment]
Is this issue open for contribution, or is this staff-only?

**Comment by naomi-lgbt** [comment]
This one is staff only due to the level of design decisions that we haven't made yet 😅
