### ISSUE TITLE
[CHORE] - Restrict slash command permissions in DMs

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1369]
### What work needs to be performed?

Currently if you use a slash command in a DM, Becca responds with a comment to use commands in a server.

We should **keep this logic** in place, as it ensures that the guild object is sent from Discord. However, we should also update all of the commands to set the DM permission to false.

This can be done at the top level command, with the `SlashCommandBuilder()` - under the `setDescription()` we should chain `.setDMPermission(false)`.

**Comment by ctoffanin** [comment]
Hi, can I be assigned to this?

**Comment by naomi-lgbt** [comment]
Sure!

**Comment by ctoffanin** [comment]
For top-level command, you mean before chaining `.addSubcommand()`, right?

**Comment by naomi-lgbt** [comment]
Yep yep
