### ISSUE TITLE
[FEAT] - Forum Channel Support for Suggestions

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1389]
### What feature would you like to see?

Forum channels are fully released and out of beta.

We should update the settings validation to allow suggestions to be posted in a forum channel.

Forums *are* threads behind the scenes, so this shouldn't take too much work 🤔

**Comment by j-dogcoder** [comment]
@naomi-lgbt Can I take this?

**Comment by naomi-lgbt** [comment]
Sure!

**Comment by naomi-lgbt** [comment]
Note that this is blocked until the config overhaul is complete

**Comment by j-dogcoder** [comment]
Ah, got it.

**Comment by j-dogcoder** [comment]
Starting now!

**Comment by j-dogcoder** [comment]
Wow... it may be super simple? I just changed line 38-40 of handle suggest from

```ts
    const suggestionChannel = guild.channels.cache.find(
      (el) => el.id === config.suggestion_channel
    ) as TextChannel;
```
to 
```ts
    const suggestionChannel = guild.channels.cache.find(
      (el) => el.id === config.suggestion_channel
    ) as TextChannel || ForumChannel ;

**Comment by j-dogcoder** [comment]
I think I may have gotten it? It is hard to test without getting all the `.env` variables worked out...

**Comment by j-dogcoder** [comment]
Draft PR coming your way now @naomi-lgbt
