### ISSUE TITLE
[CHORE] - Reduce redundant "object-exists" checks

### ISSUE THREAD

**Issue by Vyvy-vi** [BeccaLyria/discord-bot#1406]
### What work needs to be performed?

Most command handlers used by Becca require the guild object to be present and have an if statement checking for it.
Perhaps this can be extracted into the interactionCreate event handler or the `run` method of the command? We could extent the `ChatInputCommandInteraction` type of interaction attribute of `commandHandler` type into a new type that always has an associated guild object.

<img width="847" alt="Screenshot 2022-10-10 at 7 56 22 PM" src="https://user-images.githubusercontent.com/62864373/194938219-6d9389ae-c335-4b73-a354-be7f788ed50a.png">

These checks are essentialy redundant since the commandHandlers are run by the `interactionCreate` event listener only when the `guild` attribute is present.

https://github.com/BeccaLyria/discord-bot/blob/2619ac1f1aad97f0a1e9fac97d5ead97c703f501/src/events/interactionEvents/interactionCreate.ts#L42-L46

### Additional information

I'd be interested in taking up this issue.

**Comment by naomi-lgbt** [comment]
Hmm - I'm not necessarily a fan of overwriting the library type def. We could extend and mount the guild to a new property after confirming, but that feels hacky tbh.

**Comment by Vyvy-vi** [comment]
Perhaps we could add the guild object as a required argument in the `commandHandler` interface?

**Comment by naomi-lgbt** [comment]
Oh, that could work, yes.

**Comment by naomi-lgbt** [comment]
Going to go ahead and close this - I'd rather have the repetition and maintain type safety.
