### ISSUE TITLE
[FEAT] - Holiday day themed profiles pics

### ISSUE THREAD

**Issue by CBID2** [BeccaLyria/discord-bot#1422]
### What feature would you like to see?

Hi @eddiejaoude and co! Since the holiday season is starting soon, I’m thinking that 
Becca could have a specific look for some holidays (e.g., a Sailor Moon costume for Halloween, a turkey hat for Thanksgiving, A fem Santa Claus outfit for Christmas, a menorah for Hanukkah, and a top hat for New Year’s.). What do you all think? :)

**Comment by naomi-lgbt** [comment]
We would be more than happy to use holiday themed avatars, provided someone was willing to donate the art.

**Comment by CBID2** [comment]
I found this organization: https://animeforhumanity.org/about/
They do partnerships, so maybe they can form one with EddieHub somehow? By the way, I followed you on GitHub. :)

**Comment by CBID2** [comment]
> We would be more than happy to use holiday themed avatars, provided someone was willing to donate the art.

I found this organization: https://animeforhumanity.org/about/
They do partnerships, so maybe they can form one with EddieHub somehow? By the way, I followed you on GitHub. :)

**Comment by naomi-lgbt** [comment]
That organisation doesn't look like they produce art - it looks like they use existing anime and video games to call attention to mental health issues.

Also, while EddieHub does *use* this project, please note that it is actually maintained by the software development firm @nhcarrigan.

**Comment by CBID2** [comment]
> That organisation doesn't look like they produce art - it looks like they use existing anime and video games to call attention to mental health issues.
> 
> 
> 
> Also, while EddieHub does *use* this project, please note that it is actually maintained by the software development firm @nhcarrigan. 

Thanks for clarifying @naomi-lgbt. Hmmm, 🤔...I found this [Open Game Art](https://opengameart.org/content/colorless-anime-art).

**Comment by naomi-lgbt** [comment]
This is the type of feature we'd need custom art for, unfortunately.

**Comment by naomi-lgbt** [comment]
Closing as stale.
