### ISSUE TITLE
[BUG] - Localhost does not work as part of the mongo url

### ISSUE THREAD

**Issue by a2937** [BeccaLyria/discord-bot#1621]
### What bug did you encounter?

The database refuses to connect and provides a ```ECONNREFUSED ::1:27017``` error. This is directly related to an IPv4 vs IPv6 problem with Mongoose. 

### What did you expect to happen?

The default URL should have worked for generating the database then continued booting up the bot. 

### Additional information

Already have a very simple patch made.

**Comment by naomi-lgbt** [comment]
I believe this is more device-specific than Mongoose specific - ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/49394
