### ISSUE TITLE
[CHORE] - Migrate to CDN

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1645]
### What work needs to be performed?

We should migrate our images to use the CDN instead of the website.

- Update the [art command](https://github.com/BeccaLyria/discord-bot/blob/f797d311e5b693064a2d0dc4c68dfe096f3ea166/src/commands/subcommands/becca/handleArt.ts#L33) to point to `https://cdn.naomi.lgbt/becca/art/${fileName.replace(/\s/g, "%20")`
- Update the [adventure command](https://github.com/BeccaLyria/discord-bot/blob/f797d311e5b693064a2d0dc4c68dfe096f3ea166/src/commands/subcommands/becca/handleAdventure.ts#L37) to point to `https://cdn.naomi.lgbt/becca/games/${fileName.replace(/\s/g, "%20")`
- Update the [emote command](https://github.com/BeccaLyria/discord-bot/blob/f797d311e5b693064a2d0dc4c68dfe096f3ea166/src/commands/subcommands/becca/handleEmote.ts#L27) to point to `https://cdn.naomi.lgbt/becca/emotes/${fileName}`

**Comment by Susmita-Dey** [comment]
I'm working on this issue

**Comment by naomi-lgbt** [comment]
All yours~!
