### ISSUE TITLE
[FEAT] - Deprecate Habitica Command

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1661]
### What feature would you like to see?

We've moved away from Habitica for our own task management solutions - we can go ahead and deprecate the `/games habitica` command here (not sure it gets much use anyway).

To accomplish this:
- Delete the `src/commands/subcommands/games/handleHabitica.ts` file
- Update the `src/commands/subcommands/games.ts` file to remove the references to the Habitica command.
- Update the `sample.env` file to no longer include HABITICA_KEY.
- Update the `src/modules/validateEnv.ts` file to no longer require/expect HABITICA_KEY.
- Update the `src/interfaces/BeccaLyria.ts` interface to no longer include the HABITICA_KEY property on the `env` object.

**Comment by Susmita-Dey** [comment]
I wanna work on this issue

**Comment by naomi-lgbt** [comment]
Go for it!
