### ISSUE TITLE
[FEAT] - Deprecate Orbit Command

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1662]
### What feature would you like to see?

We've moved away from Orbit for our community analytics solution - we can go ahead and deprecate the `/misc orbit` command here (not sure it gets much use anyway).

To accomplish this:
- Delete the `src/commands/subcommands/misc/handleOrbit.ts` file
- Update the `src/commands/subcommands/misc.ts` file to remove the references to the Orbitcommand.
- Update the `sample.env` file to no longer include ORBIT_KEY.
- Update the `src/modules/validateEnv.ts` file to no longer require/expect ORBIT_KEY.
- Update the `src/interfaces/BeccaLyria.ts` interface to no longer include the ORBIT_KEY property on the `env` object.

**Comment by Susmita-Dey** [comment]
I wanna work on this issue

**Comment by naomi-lgbt** [comment]
Go for it!
