### ISSUE TITLE
[CHORE] - Replace all `user.tag` calls with `user.username`

### ISSUE THREAD

**Issue by naomi-lgbt** [BeccaLyria/discord-bot#1750]
### What work needs to be performed?

With the change to Discord usernames, discriminators are no longer used. While the rollout is still in place, we can go ahead and update Becca's code to reference usernames without the discriminators.

### Additional information

We should not change the `userTag` property names in the data base - just update the data saves to save the username instead.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by naomi-lgbt** [comment]
I was leaving this for first timers, but it's still unclaimed so go for it @Vyvy-vi

**Comment by sital002** [comment]
Hi, I know this issue is already assigned but its been more than 3 weeks and there is no update can I work on it.

**Comment by naomi-lgbt** [comment]
Go for it!

**Comment by sital002** [comment]
I searched user.tag and there are around 20 files should I change user.tag to user.username in all those files.
![image](https://github.com/BeccaLyria/discord-bot/assets/93700622/caffa777-ace8-478e-89c0-bd189c3cff11)

**Comment by naomi-lgbt** [comment]
Yes, that should resolve the issue.
