### ISSUE TITLE
[DOC] - Join our server link not working on docs page 

### ISSUE THREAD

**Issue by sital002** [BeccaLyria/discord-bot#1814]
### What is incorrect in the documentation?

When I was exploring the docs for local development and contributing guidelines. I tried joining the discord by click on the link but it says invalid invite link. 
This is the invite URL; https://discord.com/invite/w28Fnvyw

![image](https://github.com/BeccaLyria/discord-bot/assets/93700622/0620f16f-e25e-4fe0-bdf8-a72a96429b94)
![image](https://github.com/BeccaLyria/discord-bot/assets/93700622/eb9faec6-fc75-46dc-b2b2-67685689a811)

### What should that text say?

Can you change the invite URL link.

**Comment by naomi-lgbt** [comment]
Thanks for catching this. The invite in our redirects had expired - we've updated it.

You may need to clear your cache to see the changes.
