### ISSUE TITLE
[BUG] - messageUpdate triggering on false positives

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#528]
# Bug Report

## Describe the bug

Becca currently logs the `MESSAGE_UPDATE` event on false positives for things such as automatic link embeds or announcement channel publishes. 

## Expected behaviour

Validation needs to be added that checks if `message.content` exists on both messages AND if `oldMessage.content === newMessage.content`. If true, the code should return early to avoid logging a change that wasn't actually a change.

**Comment by nhcarrigan** [comment]
An issue with the _help wanted_ or _good first issue_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, please review our [contributing documentation](../blob/main/CONTRIBUTING.md).

If you have any issues with contributing, we are available to help in our [chat server](http://chat.nhcarrigan.com).

**Comment by bagladivyang03** [comment]
@nhcarrigan I would like to contribute to this could u pls tell me what exactly I will have to do

**Comment by nhcarrigan** [comment]
Closed via #529

**Comment by nhcarrigan** [comment]
@all-contributors please add @bagladivyang03 for code
