### ISSUE TITLE
[FEAT] change becca!star image to look good in dark and light modes

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [BeccaLyria/discord-bot#542]
# Feature Request

## Is your feature request related to a problem? Please describe:

`becca!star` command was posting a motivational message with a shiny star image. The image had a white background with a yellow star.
 
## Describe the solution you'd like

I'd suggest replacing that image with one which has a transparent background and maybe a shade of yellow that isn't too bad in both **light mode** and **dark mode**

## Screenshots
![11F74D81-6AF3-45DE-94F5-B1A8D16D0BE8](https://user-images.githubusercontent.com/61970868/109552892-ca028c80-7aeb-11eb-9b9f-11b65fe86fbd.jpeg)

**Comment by nhcarrigan** [comment]
Should be a matter of editing/replacing the image. No code changes required here.

An issue with the _help wanted_ or _good first issue_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, please review our [contributing documentation](../blob/main/CONTRIBUTING.md).

If you have any issues with contributing, we are available to help in our [chat server](http://chat.nhcarrigan.com).

**Comment by lgmontero** [comment]
If you want, you can assign me the task and I change the image so that you can see it in both dark and light mode.

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by SashoStoichkov** [comment]
Oops sorry @lgmontero I didn't saw that you'll do it 😢
