### ISSUE TITLE
[CHORE] - Update Invite Link

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#547]
# Chore Request

## Describe the work

The invite link is now redirected through Becca's domain. All instances of the invite link should be replaced with `http://invite.beccalyria.com` - including both code and documentation.

## Additional information

Existing link should be `https://discord.com/api/oauth2/authorize?client_id=716707753090875473&permissions=268527702&scope=bot`

**Comment by bagladivyang03** [comment]
@nhcarrigan I would like to solve this issue could u pls tell me exactly what all files I have to update

**Comment by nhcarrigan** [comment]
@bagladivyang03 thank you for your interest. However, the related issue is specifically reserved for first time contributors, to lower the barrier of entry for making one's first pull request to this project. 

Please watch for the issues labelled `help wanted` for things to work on. We look forward to additional contributions from you.
