### ISSUE TITLE
[BUG] - Ban command sends DM too late

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#606]
# Bug Report

## Describe the bug

The `ban` command attempts to send a DM to the user *after* banning them from the server. This causes an error because the user no longer shares a server with Becca.

## Expected behavior

The `ban` command logic needs to be switched such that the DM is sent before the user is banned.

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `src/commands/moderation/ban.ts` file:
  - Line `167` has the DM logic.
  - Line 164 has the ban action.
  - These two need to be switched.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by Zipher007** [comment]
Hi @nhcarrigan !! I want to contribute to this issue !!
So, had a doubt like do we just have to switch the ban action and the DM logic line......so that DM goes first and the action after that ?

**Comment by nhcarrigan** [comment]
That's correct, yes 🙂

**Comment by Zipher007** [comment]
Alright thanks! doing that right now...😃

**Comment by Zipher007** [comment]
had a doubt like is this the whole message for DM logic:
```
  await userToBanMentioned.send(
          `**[Ban]** ${author.toString()} has banned you for the following reason: ${reason}`
        );
```
like it is finished after this, right? Actually i've not worked with TS before, so just guessing that from a semicolon !!

**Comment by nhcarrigan** [comment]
Yep that is the full DM logic. 

`.send` is a function, which takes a string as its only argument, and the string is that template string within the `()`.

**Comment by Zipher007** [comment]
Oh! yeah I got that !!👍

**Comment by Zipher007** [comment]
Hey! so i've corrected that issue, now for the pull request, I have to provide a description and issue no. only, right ?

**Comment by nhcarrigan** [comment]
Yep! When you open the PR, there will be a template to help you :)
