### ISSUE TITLE
[FEAT] Allow Any Case Roles

### ISSUE THREAD

**Issue by krishdevdb** [BeccaLyria/discord-bot#624]
# Feature Request

## Is your feature request related to a problem? Please describe:

The role command only works with the correct case 😦 

## Describe the solution you'd like

`role.name.tolowerCase()` something like this

**Comment by nhcarrigan** [comment]
The problem with this is that Discord allows uppercase characters in role names. So if we used `toLowerCase()` then any role with an uppercase character in the name would not be self-assignable.

**Comment by krishdevdb** [comment]
We can lowercase the text message and role name both.

**Comment by nhcarrigan** [comment]
That could work - my only concern is that Discord doesn't enforce unique role names. Allowing Becca to differentiate gives server owners a bit more freedom with their roles.

**Comment by nhcarrigan** [comment]
Closing this as unneeded with the slash command migration. Thanks for reporting!
