### ISSUE TITLE
[DOC] - Update Link in PR Template

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#626]
# Incorrect Documentation

## Describe the error

The link to the documentation page currently uses the old domain. 

## Expected information

This link needs to be updated to the new domain.

**Comment by nhcarrigan** [comment]
## Good First Issue

This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `.github/PULL_REQUEST_TEMPLATE.md` file:
  - On line 26
  - Replace the `https://beccalyria.nhcarrigan.com` link with `https://www.beccalyria.com/discord-documentation`.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by vaibhavi-22** [comment]
hi @nhcarrigan I would like  to work on this issue could you  please assign me

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by SandeepKrSuman** [comment]
Hey @nhcarrigan Can I do this?

**Comment by adarsh500** [comment]
This is my first time here, can I resolve this issue ?

**Comment by prathimacode-hub** [comment]
Can I work on this issue? I'm a first timer here. @nhcarrigan

**Comment by nhcarrigan** [comment]
Thanks everyone for the interest! 

@vaibhavi-22 I am not sure why you removed your assignment - are you no longer interested in working on this?

**Comment by adityaraute** [comment]
I think people who are interested should raise a PR. I'll wait for some days, if the issue is still unresolved I'd fix it.

**Comment by adarsh500** [comment]
> I think people who are interested should raise a PR. I'll wait for some days, if the issue is still unresolved I'd fix it.

I'll start working on this asap.
