### ISSUE TITLE
[OTHER] Issue with 'level' command

### ISSUE THREAD

**Issue by shubhendumadhukar** [BeccaLyria/discord-bot#643]
# Other Issue

## Describe the issue

@nhcarrigan, I am trying to run the bot in a self hosted environment, and everything seems to be working fine, except the 'levels' commands, i.e. level, resetlevel. Following are some messages Becca responds with:
- Strange. I seem to have misplaced my records for this guild.
- I cannot toss a record that does not exist.

Not sure if it helps, but I don't see a collection corresponding to levels in my mongodb

I went through the documentation but couldn't find what could be the issue. Could you please let me know if I am missing something? I can provide additional details if required.

## Additional information

Changes I have made are only in the .env file where I have set following variables:
- DISCORD_TOKEN
- MONGODB
- NODE_ENV
- OWNER_ID
- ENCRYPTION_KEY
- SIGNING_KEY

**Comment by nhcarrigan** [comment]
The level object is created in the database the first time a message generates experience.

Once you turn on the levels feature in the config, you'll need to send a message that is *not* a bot command. That should generate the collection.

**Comment by shubhendumadhukar** [comment]
Thank you! I had missed `becca!config set levels on`.
