### ISSUE TITLE
[FEAT] Warn Command Confirmation

### ISSUE THREAD

**Issue by krishdevdb** [BeccaLyria/discord-bot#660]
# Feature Request

## Is your feature request related to a problem? Please describe:

There shoul be an confirmation for warnings

## Describe the solution you'd like

Becca should send an message like

`Are sure to command to me to cast this spell on @username for ...`

## Additional context

@nhcarrigan in EddieHub Discord

**Comment by nhcarrigan** [comment]
Thanks - will take care of this when I do some general maintenance today.
