### ISSUE TITLE
[BUG] role assignment is not working correctly

### ISSUE THREAD

**Issue by starlightknown** [BeccaLyria/discord-bot#680]
# Bug Report

The role assignment is not working if there's a space in between the words

## Screenshots

Context 
![IMG_20210707_142705](https://user-images.githubusercontent.com/74637789/124731218-a8009700-df2f-11eb-9886-2f728f8dc4dc.jpg)

**Comment by nhcarrigan** [comment]
Probably an issue with the way the command arguments are parsed. Will look in to it sometime this week.

**Comment by nhcarrigan** [comment]
Resolved via #684
