### ISSUE TITLE
[FEAT] Add the ability to check others' levels

### ISSUE THREAD

**Issue by Panquesito7** [BeccaLyria/discord-bot#688]
# Feature Request

## Is your feature request related to a problem? Please describe

It'd be cool if you could check others' levels. I tried doing `becca!level <username>` and it only showed up my level. I thought it was possible to do this, and I would like to see this feature implemented. 🙂

## Describe the solution you'd like

I would like the command to accept parameters (e.g.: `becca!level nhcarrigan`, and it shows up nhcarrigan's level).

**Comment by nhcarrigan** [comment]
Hmmm, I need to think on this a bit.

The logic itself isn't too complex, but the resulting UX will result in a lot of extra user pings.

**Comment by Panquesito7** [comment]
Yeah, it would ping a lot of people. I would also like to be able to check other's level/user info with just their username and tag.

**Comment by nhcarrigan** [comment]
That's not possible, because the database doesn't store that.

You would be able to pass an ID, but not a raw username/tag.
