### ISSUE TITLE
[OTHER] - Test

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#693]
### What would you like to share?

This is just to test how issue forms render when submitted.

### Additional information

Nope!

**Comment by nhcarrigan** [comment]
Interesting so the description field disappears. I like that - very handy.

**Comment by nhcarrigan** [comment]
So do the markdown fields. Hmmm.

**Comment by Panquesito7** [comment]
Hmm, so your idea was to keep the Markdown fields, right? 🤔

**Comment by nhcarrigan** [comment]
Nope. I think I can live without those.

**Comment by nhcarrigan** [comment]
This is clean and will make reporting issues and feature requests smoother for non-developers, I think.

**Comment by Panquesito7** [comment]
Can I make an issue test, too? I would like to see how it works! 😄

**Comment by nhcarrigan** [comment]
Go for it!
