### ISSUE TITLE
[FEAT] - Update the Sus command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#710]
### What feature would you like to see?

The `sus` command should be updated to include the two missing colours: `coral` and `banana`.

The changes should be made in the `src/config/commands/SusList.ts` file, with the colour names going in `SusNames` and the colour HEX values going in `SusColours`. Note that order does matter - the name and matching hex must have the same index.

Bonus points are awarded for renaming `SusList.ts` to `susList.ts` and updating the import statement in the `src/commands/games/sus.ts` file.

### Additional information

![image](https://user-images.githubusercontent.com/63889819/127044948-ca2da1c7-9faf-4004-81c6-2c9d2a59a1e4.png)

This can be used to grab HEX codes for the missing colours.

**Comment by jayesh-srivastava** [comment]
Hi @nhcarrigan , I would like to work on this issue. Can you please assign me the same?

**Comment by nhcarrigan** [comment]
All yours!

**Comment by jayesh-srivastava** [comment]
Thank you @nhcarrigan

**Comment by jayesh-srivastava** [comment]
Hey @nhcarrigan, I have made two PRs for the issue. Needs your approval : )

**Comment by nhcarrigan** [comment]
Closed via #711
