### ISSUE TITLE
[FEAT] - Economy System

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#721]
### What feature would you like to see?

Going to build out an economy system!

- Gain coins based on activity in server (similar to level system)
- Coins are global - coins you earn in one server are available in all servers
- Add game commands to use the coins
- Possible collectible items?
- Configurable rewards? 

Lot of potential here, and much to consider.

**Comment by adityaraute** [comment]
Sounds a lot of fun. Biggest challenge might be to maintain the second bullet.

**Comment by nhcarrigan** [comment]
Closed via the initial prototype in #761
