### ISSUE TITLE
[BUG] - Becca doesn't allow to share gif's

### ISSUE THREAD

**Issue by shreemaan-abhishek** [BeccaLyria/discord-bot#729]
### What bug did you encounter?

When I attempt to share a GIF it assumes it as a tenor link (well, it's actually a tenor link tho). And says "You are not allowed to share links here, unless it is a GitHub link. Create a discussion on our support repo if you have resources to share!"

### What did you expect to happen?

It should have allowed me to share the gif.

### Screenshots

![image](https://user-images.githubusercontent.com/61597896/128629099-a67ec8ac-8017-4228-a622-e126c5944db5.png)

**Comment by nhcarrigan** [comment]
Allowed link domains are configured on a per-server basis. Closing this as it is not an issue with the code. 🙂
