### ISSUE TITLE
[FEAT] - Level Ignore channels 

### ISSUE THREAD

**Issue by j-dogcoder** [BeccaLyria/discord-bot#746]
### What feature would you like to see?

The ability for Becca to bot count messages in specified channels towards the level system. 

### Additional information

As talked about in [https://discord.com/channels/778130114772598785/778144772929093643/875739687204048907](https://discord.com/channels/778130114772598785/778144772929093643/875739687204048907)

**Comment by nhcarrigan** [comment]
Will likely implement this as a `level_ignore` setting, which allows servers to set specific channels that Becca will not grant experience for.

**Comment by j-dogcoder** [comment]
That was my thought also.

**Comment by nhcarrigan** [comment]
Blocking this until migration is complete.

**Comment by nhcarrigan** [comment]
This is ready for contribution! Be sure to update your fork if you have an existing one.
