### ISSUE TITLE
[FEAT] - Poll Commands

### ISSUE THREAD

**Issue by krishdevdb** [BeccaLyria/discord-bot#749]
### What feature would you like to see?

A poll command similar to game command
![image](https://user-images.githubusercontent.com/76587897/129469381-79f3177f-9985-4487-a206-40ed030c8aa3.png)

**Comment by nhcarrigan** [comment]
Very excited to implement this. However, blocking until after migration is complete.

**Comment by nhcarrigan** [comment]
This is ready for contribution! Be sure to update your fork if you have an existing one.
