### ISSUE TITLE
[BUG] - Embedded Messages

### ISSUE THREAD

**Issue by AbhijithGanesh** [BeccaLyria/discord-bot#793]
### What bug did you encounter?

Initially, I sent messages which contained lines of code and I used discord's embedded message feature for syntax highlighting. I thought it was the code which had slashes that got removed but it removed the other samples without forward slashes too.

### What did you expect to happen?

I expected the bot to validate the message and not remove my message.

### Screenshots

![image](https://user-images.githubusercontent.com/67182544/131808113-2c332cc8-60b7-441b-b32b-8cf003c943ff.png)

**Comment by AbhijithGanesh** [comment]
It allows the user to edit the message and doesn't delete if edited.

**Comment by nhcarrigan** [comment]
Going to close this as a wontfix, because ignoring code blocks would completely defeat the point of the link detection.
