### ISSUE TITLE
[CHORE] - Please create a bot webpage and like the OAuth to allow other servers.

### ISSUE THREAD

**Issue by AbhijithGanesh** [BeccaLyria/discord-bot#819]
### What work needs to be performed?

We need a webpage and OAuth permission to add Becca to other servers

**Comment by nhcarrigan** [comment]
Could you provide more information?

Becca has a website at https://dash.beccalyria.com, can be invited with https://invite.beccalyria.com, and admin tools are potentially planned in #727

**Comment by AbhijithGanesh** [comment]
I am sorry for this Issue being created. I didn't know the existence of #727

**Comment by nhcarrigan** [comment]
No worries!

Going to close this issue then 🙂
