### ISSUE TITLE
[FEAT] - Manual Experience Point Grants

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#826]
### What feature would you like to see?

Grant server managers the ability to award and remove experience.

This should be a *sub-command* under the existing `manage` top-level command. The sub-command should be called `xpmodify`, and should:

- Take a `user` option for the user to modify. Name this `user`.
- Take a `number` (NOT integer) option for the amount to adjust the XP by. Name this `adjustment`.
- The helper module should assert that the caller has the `MANAGE_SERVER` permission
- The helper module should assert that the adjustment would neither reduce the user's XP below 0 or increase it above the level cap.
- If all checks pass, the helper module should adjust the user's XP by the `adjustment` amount and save it.

**Comment by 5antos** [comment]
Hey, may I claim this one? 😛

**Comment by nhcarrigan** [comment]
All yours!

Do note that contributions made before October 1st will not count for hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)

**Comment by 5antos** [comment]
Hey!

I'm sorry, unfortunately I can't, sorry for not keeping you updated about it.

Anyways, wish you good luck for this project!

**Comment by nhcarrigan** [comment]
No worries - hope your hacktoberfest is going well!

**Comment by Vyvy-vi** [comment]
😅  I forgot about this, I might open a PR for this later today...

**Comment by nhcarrigan** [comment]
No worries!

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-12-01 at 8 12 28 PM](https://user-images.githubusercontent.com/62864373/144254933-d0370e45-2f97-4088-aba7-e8858f52f227.png)
![Screenshot 2021-12-01 at 8 12 10 PM](https://user-images.githubusercontent.com/62864373/144254947-ae5102c7-2bb2-4a1a-87e3-402796d128a3.png)

would an option for add/remove be alright, or would it be preferred to deal with positive and negative numbers?

**Comment by nhcarrigan** [comment]
I think an option is fine 🙂
