### ISSUE TITLE
[CHORE] - Update XP Cooldown

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#827]
### What work needs to be performed?

The XP Cooldown should be updated from one minute to five minutes.

To make this change:

- Update [this line](https://github.com/BeccaLyria/discord-bot/blob/8f038cb7db6ccd53a31ae1a72cbf5d14feb34928/src/listeners/levelListener.ts#L78) to use `300000` instead of `60000`.

### Additional information

Docs will need to be updated as well.

**Comment by Starlight220** [comment]
I guess I could take this?

**Comment by nhcarrigan** [comment]
All yours!

Do note that pull requests opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)

**Comment by Shivaminc** [comment]
I want to work on this issue.

**Comment by nhcarrigan** [comment]
Hi there! 

This issue has already been claimed by another contributor. 

You're welcome to browse our other open issues - look for ones that aren't assigned yet. 

If you have questions, feel free to join [our support server](https://chat.nhcarrigan.com)
