### ISSUE TITLE
[CHORE] - Update Message Logs

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#828]
### What work needs to be performed?

Update the message deletion and message edit logs to include the channel name, and the edit logs to include the message link.

To complete this:

- In [this file](https://github.com/BeccaLyria/discord-bot/blob/main/src/events/messageEvents/messageUpdate.ts) add a field to the `updateEmbed` with the name `Channel` and the value `<#${newMessage.channel.id}>`.
- Add another field to that `updateEmbed` with the name `Message link` and the value `newMessage.url`.
- In [this file](https://github.com/BeccaLyria/discord-bot/blob/main/src/events/messageEvents/messageDelete.ts) add a field to the `deleteEmbed` with the name `Channel` and the value `<#${channel.id}>`.

**Comment by Akshu-on-github** [comment]
May I snag this one for Hacktoberfest?

**Comment by nhcarrigan** [comment]
All yours :)
