### ISSUE TITLE
[FEAT] - Add Command Leaderboard

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#830]
### What feature would you like to see?

This is a big one. We will want to:

- Create a new database schema that tracks overall command usage per server. The schema should track the `serverId`, `serverName`, and `commandUses`.
- Create a new listener called `commandListener` which receives Becca and the interaction and increments the `commandUses` for that `serverId` (also update the `serverName` so it's up to date).
- Run that listener in the `interactionCreate` event within the logic block for `interaction.isCommand()`. Run before the command logic.
- Add a new command `/becca stats`, and add a `string` options with `choices`. The only choice now will be `Command Leaderboard` with a value of `commands`.
- Add a handler for the `stats` subcommand called `handleStats`. If the choice is `commands`, return an embed with the top ten servers by `commandUses`.

### Additional information

Once Becca reaches verification we plan to list her on top.gg, and can expand this command to track votes too!

**Comment by bradtaniguchi** [comment]
I could do this for hacktober. However, I think each of the above steps could be its own issue/pr.

It also might make sense to transition these to a task-list, that can be "spun out" into their own issues?
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

This should cut down on the amount of work required for 1 person to get 1 pr for all of these tasks. 

I believe the "Add new command" would be the final "step" that would open up the feature to user's of the bot, until then all the other tasks can take their time.

**Comment by Vyvy-vi** [comment]
I think this can be split into two tasks:
- [ ] Tracking Command Usage
  > * Create a new database schema that tracks overall command usage per server. The schema should track the `serverId`, `serverName`, and `commandUses`.
  > * Create a new listener called `commandListener` which receives Becca and the interaction and increments the `commandUses` for that `serverId` (also update the `serverName` so it's up to date).
  > * Run that listener in the `interactionCreate` event within the logic block for `interaction.isCommand()`. Run before the command logic.

- [ ] Add a new command for getting stats for command usage
  > * Add a new command `/becca stats`, and add a `string` options with `choices`. The only choice now will be `Command Leaderboard` with a value of `commands`.
  > * Add a handler for the `stats` subcommand called `handleStats`. If the choice is `commands`, return an embed with the top ten servers by `commandUses`.

**Comment by nhcarrigan** [comment]
Yep that's a good approach.

@bradtaniguchi hello! You're welcome to tackle one or both of those if you want 🙂

**Comment by Vyvy-vi** [comment]
If Brad's not tackling both, I would love to help out :)

**Comment by bradtaniguchi** [comment]
> If Brad's not tackling both, I would love to help out :)

I can start out on the database feature probably tomorrow morning with setting everything up in a codepsace fork. I have a few hours then, I'll provide an update then. Otherwise your welcome to work on the 2nd part, (the command) otherwise if you want to do the reverse let me know :D

**Comment by bradtaniguchi** [comment]
Just a quick update, I'm still moving through setting up the bot and getting it running. While doing so, running into a few roadblocks here and there from the docs/setup steps and have been roughing those edges out. (like the above NASA_KEY issue)

Will try to continue with that progress later today. (8 hours from this post)

**Comment by bradtaniguchi** [comment]
Another update

I ran into more issues setting up my instance of the bot, but documented what I found to the best of my ability (see: https://github.com/BeccaLyria/discord-documentation/issues/564). With that I was able to get the bot running 😄, however I'm done for tonight, and will move onto the actual database schema feature tomorrow.

I mainly want to keep @Vyvy-vi updated with the progress as I know they are essentially waiting for that part to be done 👍

**Comment by bradtaniguchi** [comment]
Can't get to it today or tomorrow, will spend time for it Thursday tho 👍

**Comment by bradtaniguchi** [comment]
I'm starting work on the actual feature and have some questions about the spec:

> Create a new database schema that tracks overall command usage per server. The schema should track the serverId, serverName, and commandUses.

Do we want to keep track of each command at all? Or just command usage in general?

**Comment by nhcarrigan** [comment]
We just want to track overall command usage (both slash commands and context menu commands, all lumped into one total)

**Comment by Vyvy-vi** [comment]
I would open up a PR for that today/tomorrow

I'm wondering, would it be advised for me to checkout your pr's branch, and work on from there? (*This might cause issues with the history though)

Or should I wait for it to be merged, and then test the command?
