### ISSUE TITLE
[FEAT] - Show Version Number In `updates`

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#835]
### What feature would you like to see?

The `/becca update` command should show the current version number. This can be added to the `updateEmbed` within the `handleUpdates` file. A field should be added between the "Latest Updates" and "Next Scheduled Update" fields. The new field should have the name "Current Version" and the value `process.env.npm_package_version` to keep the result dynamically updated.

**Comment by princeprag** [comment]
@nhcarrigan I would like to work on it!

**Comment by nhcarrigan** [comment]
@princeprag all yours!

Do note that pull requests opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)

**Comment by gdeep-ciena** [comment]
Please assign

**Comment by princeprag** [comment]
@gdeep-ciena , I am already working on it bro.. Maybe you should find a issue which is still unclaimed :)

**Comment by nhcarrigan** [comment]
Correct.

@gdeep-ciena this issue has already been claimed by another contributor - you're welcome to browse our other issues, look for ones that do not have someone assigned yet 🙂
