### ISSUE TITLE
[FEAT] - Data Cleanup on Member Leave

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#837]
### What feature would you like to see?

When a member leaves a guild (`memberRemove` event), we should clean their data for that guild. 

We need a new module called `memberRemoveCleanup` that runs in the `memberRemove` event. It should take Becca, the member ID, and the guild ID as arguments, and should:

- See if the member has level data in the server - if so, delete their record.
- See if the member has star data in the server - if so, delete their record.

No other data should be removed.

The new module should go in `src/modules/guild/memberRemoveCleanup.ts` and be imported into the `src/events/member/memberRemove.ts` logic.

**Comment by IsaacArcos248** [comment]
I'd like to take this one on, nhcarrigan!

**Comment by nhcarrigan** [comment]
Assigned!

**Comment by nhcarrigan** [comment]
Closed in #865
