### ISSUE TITLE
[FEAT] - Emote Command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#842]
### What feature would you like to see?

We should create a new `emote` command - this can be a subcommand of `/becca`.

This command should grab a random emote from the `emoteList.ts` array and construct an embed where:
- The `name` is used in the title as `Becca is ${name}`
- The `description` is used as the description
- The `url` is used as the image (not thumbnail).
- The `footer` has the text `Art by Starfazers: https://starfazers.art`.

### Additional information

A PR which resolves this should *not* add data to the `emoteList` array - this will be done by staff after the command is written.

**Comment by neel229** [comment]
I would like to work on it

**Comment by nhcarrigan** [comment]
All yours!

Do note that PRs opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, join [our support server](https://chat.nhcarrigan.com)!

**Comment by nhcarrigan** [comment]
@neel229 you removed your assignment are you no longer interested in working on this?

**Comment by neel229** [comment]
Yes, I would like to work on issues in Go.

**Comment by nhcarrigan** [comment]
Sounds good - best of luck in your Hacktoberfest contributions! 😁

**Comment by nhcarrigan** [comment]
All yours!

Do note that PRs opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, join [our support server](https://chat.nhcarrigan.com)!

**Comment by qwe123coder** [comment]
> * The `description` is used as the description
> * The `url` is used as the image (not thumbnail).


hey how will I find out the use description and the URL of the emote ??

**Comment by nhcarrigan** [comment]
Those are properties of the objects within `emoteList.ts`, which has an example object you can use for testing.

Once the command is in place, I will populate the `emoteList` with the live data myself.

**Comment by qwe123coder** [comment]
> Those are properties of the objects within `emoteList.ts`, which has an example object you can use for testing.
> 
> Once the command is in place, I will populate the `emoteList` with the live data myself.

hey, where is emotelist.ts located ??

**Comment by nhcarrigan** [comment]
`src/config/commands/emoteList.ts`

**Comment by qwe123coder** [comment]
sorry 

i realy wanted to contribute but could not :(

**Comment by nhcarrigan** [comment]
Heya @Vyvy-vi,

Just checking in to see if you are still working on this.
