### ISSUE TITLE
[CHORE] - Update Becca's Status

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#844]
### What work needs to be performed?

It's time to update Becca's status.

[This line](https://github.com/BeccaLyria/discord-bot/blob/52d4fd9ea784ac81e654eca78d4044959ca2645e/src/index.ts#L79) should be modified to replace the "for people who need my `/help`~!" text with "over your guild".

**Comment by DireWolf707** [comment]
Hye, I am new to open source and want to contribute to this issue for hacktoberfest.
So, can you please Assign this issue to me?

**Comment by nhcarrigan** [comment]
All yours!

Do note that if you are looking for Hacktoberfest contributions, PRs will not count if they are opened before the event starts.

Additionally, if you have any questions about the contributing process, we recommend joining our [support server](https://chat.nhcarrigan.com).
