### ISSUE TITLE
[CHORE] - Becca profile command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#845]
### What work needs to be performed?

The `/becca becca` command should be renamed to `/becca profile`. 

In order to accomplish this:
- [This line](https://github.com/BeccaLyria/discord-bot/blob/52d4fd9ea784ac81e654eca78d4044959ca2645e/src/commands/becca.ts#L63) must be updated to replace `becca` with `profile`.
- [This line](https://github.com/BeccaLyria/discord-bot/blob/52d4fd9ea784ac81e654eca78d4044959ca2645e/src/commands/becca.ts#L100) must be changed to `case "profile":`
- The [`handleBecca`](https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/commands/subcommands/becca/handleBecca.ts) file should be renamed to `handleProfile`.
- [This line](https://github.com/BeccaLyria/discord-bot/blob/52d4fd9ea784ac81e654eca78d4044959ca2645e/src/modules/commands/subcommands/becca/handleBecca.ts#L12) should be updated to `export const handleBecca`.
- Within that same file, the `beccaEmbed` should be renamed to `profileEmbed`.
- The import in the `becca` command file will need to be updated to match this change.

**Comment by Pranjalmishra30** [comment]
Hey, i would like to conribute to this repo by working on this issue. 
Also would it be allright, if i submit my PR on Oct 1. (so that they count for hacktoberfest)
Thanks.

**Comment by nhcarrigan** [comment]
All yours!

You can absolutely wait to submit your PR until the event starts 🙂 

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)
