### ISSUE TITLE
[FEAT] - Donate Command

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#850]
### What feature would you like to see?

The donate command should be updated to use link buttons!

Within the [handleDonate.ts file](https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/commands/subcommands/becca/handleDonate.ts), create three new `MessageButton()` components using the `link` style, one for each of the fields on the embed.

The buttons need to be added to a `MessageActionRow()`, which gets passed to the `interaction.editReply()` call as the `components` property (in an array).

The fields can then be removed from the embed.

### Additional information

[Example](https://github.com/RosaliaNightsong/discord-bot/blob/main/src/modules/subcommands/rosalia/handleDonate.ts)

**Comment by DeltaXWizard** [comment]
Heya!

I'd like to contribute to this project by working on this issue if you don't mind :)

**Comment by nhcarrigan** [comment]
All yours!

Do note that PRs made before October 1st are not eligible for Hacktoberfest.

If you have questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)
