### ISSUE TITLE
[CHORE] - Update CDN Links

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#851]
### What work needs to be performed?

We migrated our CDN to a new server and changed some of the file structure. A couple of links in Becca's code need to be updated.

- [In the `handleStar.ts` file](https://github.com/BeccaLyria/discord-bot/blob/11f2076f0cb9532e6e1d6fa94b6a587edec6eaa1/src/modules/commands/subcommands/community/handleStar.ts#L77) the link should be updated to `https://cdn.nhcarrigan.com/content/projects/star.png`
- [In the `handleMtg.ts` file](https://github.com/BeccaLyria/discord-bot/blob/11f2076f0cb9532e6e1d6fa94b6a587edec6eaa1/src/modules/commands/subcommands/games/handleMtg.ts#L35) the link should be updated to `https://cdn.nhcarrigan.com/content/projects/mtg.jpg`

**Comment by CTZxVULKAN** [comment]
Project seems quiet fun.
Let me work on it ?

**Comment by nhcarrigan** [comment]
All yours!

Do note that PRs opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)
