### ISSUE TITLE
[BUG] - Commands not loaded in development

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#853]
### What bug did you encounter?

When refactoring Becca for production, we modified the logic such that she would not reload her commands on startup.

This is ideal for production, but not ideal for development.

### What did you expect to happen?

In the `index.ts`, we will need to add a step after loading the commands to check if `NODE_ENV !== "production"`, and if true, call the `registerCommands` utility.

**Comment by gitaalekhyapaul** [comment]
Hi, I would like to take up this issue :wave:, kindly assign it to me!

**Comment by nhcarrigan** [comment]
All yours!

Note that PRs created before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)
