### ISSUE TITLE
[FEAT] - More Voice Events

### ISSUE THREAD

**Issue by L0SER8228** [BeccaLyria/discord-bot#854]
### What feature would you like to see?

Some more voice states events

- **voice mute** - when a member has been voice muted (self mute or server mute)
- **voice unmute** - when a member has been voice unmuted (self unmute or server unmute)

- **voice deaf** - when a member has been voice deafed (selfDeaf or serverDeaf)
- **voice undeaf** - when a member has been voice undeafed (self Undeaf or server Undeaf)

### Additional information

Actually I would like to add this Features, if you think this could be useful

**Comment by nhcarrigan** [comment]
Sure, sounds good.

This logic should go in the `voiceStateUpdate.ts` file, and will need to occur within the `if (oldState.channelId === newState.channelId)` block.

**Comment by L0SER8228** [comment]
> Sure, sounds good.
> 
> This logic should go in the `voiceStateUpdate.ts` file, and will need to occur within the `if (oldState.channelId === newState.channelId)` block.

No, it cannot be . 
I found that we can remove this and add an additional check on voice move state `oldState.channelId !== newState.channelId`

**Comment by nhcarrigan** [comment]
Yeah that could work too. Good idea.
