### ISSUE TITLE
[FEAT] - NASA API key should be optional, but is required

### ISSUE THREAD

**Issue by bradtaniguchi** [BeccaLyria/discord-bot#867]
### What bug did you encounter?

Running the bot without the NASA api key is not possible, due to:
https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/validateEnv.ts#L32-L34

even though the docs, and the `sample.env` say its optional.

### What did you expect to happen?

The bot should just print out a warning, or do nothing and let me run the bot.

**Comment by nhcarrigan** [comment]
Yeah this has been on my list for a while lol.

The `return` statement should be removed, and replaced with a `beccaLogHandler.log("warn", "Missing NASA API key");`.
The [config assignment](https://github.com/BeccaLyria/discord-bot/blob/c9a23df79d91f99caaf7a99a6daf7d8a74af6dfa/src/modules/validateEnv.ts#L53) should be given a fallback of an empty string.
Ideally, the [command logic](https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/commands/subcommands/misc/handleSpace.ts) will assert the key exists and return a message to the user if it does not.

**Comment by bradtaniguchi** [comment]
I can work on this first before moving onto #830 👍

**Comment by nhcarrigan** [comment]
All yours 🙂
