### ISSUE TITLE
[CHORE] - Update PR template to redirect directly to contributing site, rather than CONTRIBUTING file

### ISSUE THREAD

**Issue by bradtaniguchi** [BeccaLyria/discord-bot#869]
### What work needs to be performed?

Change the `PULL_REQUEST_TEMPLATE.md` file's contributing guidelines link to redirect directly to the [contributing site](https://docs.beccalyria.com/#/contribute.md) rather than the CONTRIBUTING file, as the file's only contents are primarily to link to the [Developer Certificate of Origin](https://developercertificate.org/) and the contributing site (linked above).

### Additional information

Maybe it's intended to be a 2 step flow, as I'm not sure if the developer certificate of origin is provided in the site anywhere? If its intended, then this issue can be closed as its intended 👍

**Comment by nhcarrigan** [comment]
This pull request template should be changed as indicated above - a PR to resolve this is welcome but won't be merged until https://github.com/BeccaLyria/discord-documentation/issues/560 is resolved.

**Comment by MukulKolpe** [comment]
Hey @nhcarrigan can I work on this issue?

**Comment by nhcarrigan** [comment]
All yours! Note that your PR will be blocked until the linked doc issue is complete 🙂
