### ISSUE TITLE
[FEAT] - OWNER_ID key should be optional, but is required

### ISSUE THREAD

**Issue by bradtaniguchi** [BeccaLyria/discord-bot#870]
### What feature would you like to see?

Running the bot without the NASA api key is not possible, due to:
https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/validateEnv.ts#L36-L38

even though the docs, and the sample.env say its optional.

### Additional information

This is more or less the same underlying issue as #868 

I can leave this one for someone else to work on it as well for their hacktoberfest contributions, or I can integrate it into the above linked issue?

**Comment by nhcarrigan** [comment]
This should be flipped, I think.

With the migration to slash commands, the `nhcarrigan` admin commands are locked to the OWNER_ID, as is the `emergency reload` text command.

This should be marked as required in the `sample.env` and on the docs.

**Comment by ankeshp03** [comment]
Hi @nhcarrigan, I have changed the `OWNER_ID` in the Doc, should I work on this issue as well?

**Comment by nhcarrigan** [comment]
Sure!
