### ISSUE TITLE
[OTHER] - Add back-up rejection/exception handlers to handle startup errors

### ISSUE THREAD

**Issue by bradtaniguchi** [BeccaLyria/discord-bot#875]
### What would you like to share?

While setting up the bot locally I was able to trip up some exceptions during startup due to a range of mis-configurations and my own mess-ups where I got nasty/ugly error/unhelpful errors like:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/workspaces/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/workspaces/discord-bot/node_modules/discord.js/src/client/Client.js:245:7)
```

These could be handled with the following handlers:
https://github.com/BeccaLyria/discord-bot/blob/dcc1b5bb4110e240ed14a69c56a9a9219368838f/src/index.ts#L97-L103

Except because these are setup **after** all the initialization occurs, they aren't setup in time and thus the above ugly errors appear.

### Additional information

I think setting up two versions, a basic logger that is available to at least log the errors can be added to deal with initialization errors, and then the current "becca" version's are added once the bot is up and running to get better information.

I would think there is a way to remove the default/basic ones that would need to be added to log unhandledExceptions/promiseRejections after they are declared, otherwise I think they are "merged", which may or may not be optimal.

**Comment by nhcarrigan** [comment]
Realistically, the `beccaErrorHandler` only needs the `debugHook` value so these could be mounted just after the webhook is instantiated.

**Comment by Vyvy-vi** [comment]
I would like to work on this.

**Comment by nhcarrigan** [comment]
Go for it!
