### ISSUE TITLE
[FEAT] - Include Command Data in Server Cleanup

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#885]
### What feature would you like to see?

When Becca is removed from a server, she currently cleans up the server's data. The new `CommandModel` needs to be included in the data cleanup.

In `src/events/guildEvents/guildDelete.ts`, add a `CommandModel.findOneAndDelete` call similar to the others.

**Comment by toth2000** [comment]
Looking into  this.
