### ISSUE TITLE
[CHORE] - Roll Thanks listener into sass mode

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-bot#889]
### What work needs to be performed?

The thanks listener is rather sassy, and can be rolled into the sassy mode config.

- Remove the `thanks` setting
- Merge the `thanksListener` logic into the `sassListener` logic.

### Additional information

A heads up that I'm doing some refactoring today, so you may want to wait to fork + start on this until after.

**Comment by nhcarrigan** [comment]
Heya @Vyvy-vi.

Just checking in to see if you're still working on this.

**Comment by Vyvy-vi** [comment]
I am..
Got a bit sidetracked 😅

I would open a PR in an hour or so 👍

**Comment by nhcarrigan** [comment]
If possible, would prefer focus on the Emote command first - would love to include that one in Monday's deployment.
