### ISSUE TITLE
[BUG] - If user not found, don't show achievements

### ISSUE THREAD

**Issue by krishguptadev** [BeccaLyria/discord-bot#957]
### What bug did you encounter?

![image](https://user-images.githubusercontent.com/91655303/139568443-f5470c18-7c15-4137-bef0-7e5ccc64b013.png)

### What did you expect to happen?

Not show achievements

**Comment by nhcarrigan** [comment]
This would be nice to have, but needs to be implemented in a way that doesn't increase the cognitive complexity of the function.

**Comment by Vyvy-vi** [comment]
I'd like to take a stab at this...

**Comment by nhcarrigan** [comment]
I think the best approach would be to:

https://github.com/BeccaLyria/discord-bot/blob/38c0d8a4bd0df59d7ef69965e69bc3cc1ec21baa/src/modules/commands/subcommands/games/handleHabitica.ts#L21

Check if the `userEmbed.title` is equal to `User not found!`, and if so, do an `interaction.editReply` to send just that embed (before the achievement embed is even generated) and return early.

**Comment by Vyvy-vi** [comment]
How about something like this? (:thinking: might be a bit less readable though)
```
    habiticaEmbeds[0] = await generateHabiticaUser(Becca, id, headers);
    if (habiticaEmbeds[0].title !== "User not found!") {
      habiticaEmbeds[1] = await generateHabiticaAchievements(
        Becca,
        id,
        headers
      );
    }

    await interaction.editReply({ embeds: habiticaEmbeds });
```

**Comment by nhcarrigan** [comment]
Yep that should work
