### ISSUE TITLE
[FEAT] - Add a vote server button

### ISSUE THREAD

**Issue by krishguptadev** [BeccaLyria/discord-bot#958]
### What feature would you like to see?

Add a vote server button here: 
![image](https://user-images.githubusercontent.com/91655303/139568675-dfc6652d-c53b-4b10-a847-9da09b8014d4.png)

**Comment by nhcarrigan** [comment]
Not likely to implement this for the server votes. The link is available in the server, and we *want* people to join the server.

**Comment by krishguptadev** [comment]
> Not likely to implement this for the server votes. The link is available in the server, and we _want_ people to join the server.
> 
> Will have a think on this one.

But it would be taunting to scroll upwards regularly to vote :) Maybe add a server only something for this?

**Comment by nhcarrigan** [comment]
Becca already has vote reminders which launched in this same update.

**Comment by krishguptadev** [comment]
> Becca already has vote reminders which launched in this same update.

So Becca would dm me? I didn't got any DMs since then 🤔

**Comment by nhcarrigan** [comment]
It just launched. And doesn't start reminding you until you vote again. And it'll send in the same channel as the "thanks for voting" message.

**Comment by nhcarrigan** [comment]
Alright, let's go for it.

We should add two buttons to this response:
The first should have a link to join the server.
The second should have a link to vote for the server.
