### ISSUE TITLE
[FEAT] - Allow to get non-cached response

### ISSUE THREAD

**Issue by krishguptadev** [BeccaLyria/discord-bot#959]
### What feature would you like to see?

Add an optional parameter for getting a non-cached response.

**Comment by nhcarrigan** [comment]
I'm assuming this is for the orbit command? (Recommend slowing down and taking time to write detailed issues 🙂 )

If so, then we will not be implementing that. Due to the way the API is configured, the command currently requires 16 consecutive API calls to pull the data, which is why we cache it.

**Comment by krishguptadev** [comment]
> I'm assuming this is for the orbit command? (Recommend slowing down and taking time to write detailed issues 🙂 )
> 
> If so, then we will not be implementing that. Due to the way the API is configured, the command currently requires 16 consecutive API calls to pull the data, which is why we cache it.

But I think there should be an ability to fetch a non-cached response or refresh the stats periodically?

**Comment by nhcarrigan** [comment]
Stats will be refreshed when I bust the cache naturally during the weekly deployment. This is slow moving data anyway, so there shouldn't be a need for more frequent updates.
