### ISSUE TITLE
[FEAT] -  Discord Together Activity

### ISSUE THREAD

**Issue by L0SER8228** [BeccaLyria/discord-bot#961]
### What feature would you like to see?

Some discord together activity, such as watch together, doodlecrew, poker, fishington etc

### Additional information

Watch together activity alows to watch YouTube with friends together jn a Voice channel. Similarly others activity allows to play game with friends in a discord voice channel.

And I would like to add this features, if you found useful

**Comment by nhcarrigan** [comment]
We will not be implementing these as these are an experimental feature in Discord.

When ready, Discord will launch these natively. Until then, we're not going to build features that grant early access to Discord things.
